/**
 * Renders a Lucide icon from its kebab-case name string as stored in the DB.
 * Falls back to a Tag icon for unknown names.
 */
import {
  Tag, ShoppingCart, ShoppingBag, Utensils, UtensilsCrossed, Car, Home,
  Heart, Briefcase, Gamepad2, Zap, BookOpen, Music, Plane, Coffee, Gift,
  TrendingUp, DollarSign, CreditCard, Wallet, Bus, Train, Film, Tv,
  Smartphone, Monitor, Laptop, Wrench, Scissors, Shirt, Baby, Bike,
  Pizza, Apple, Leaf, Sun, Moon, Star, Sparkles, Package, Box,
  Building, Building2, GraduationCap, Stethoscope, Pill, Dumbbell,
  Fuel, Receipt, Banknote, Coins, PiggyBank, Landmark, Percent,
  ShoppingBasket, Globe, MapPin, Camera, Headphones, Watch, Gem,
  Hammer, Lightbulb, Wifi, Phone, Mail, Send, Truck, Anchor, Flame,
  Snowflake, Umbrella, Cloud, Wind, Trees, Flower2, Dog, Cat,
  Salad, IceCream, Beer, Wine, Sandwich, Soup, Bookmark,
} from 'lucide-react'

const iconMap = {
  'tag':              Tag,
  'shopping-cart':    ShoppingCart,
  'shopping-bag':     ShoppingBag,
  'shopping-basket':  ShoppingBasket,
  'utensils':         Utensils,
  'utensils-crossed': UtensilsCrossed,
  'car':              Car,
  'home':             Home,
  'heart':            Heart,
  'briefcase':        Briefcase,
  'gamepad-2':        Gamepad2,
  'zap':              Zap,
  'book-open':        BookOpen,
  'music':            Music,
  'plane':            Plane,
  'coffee':           Coffee,
  'gift':             Gift,
  'trending-up':      TrendingUp,
  'dollar-sign':      DollarSign,
  'credit-card':      CreditCard,
  'wallet':           Wallet,
  'bus':              Bus,
  'train':            Train,
  'film':             Film,
  'tv':               Tv,
  'smartphone':       Smartphone,
  'monitor':          Monitor,
  'laptop':           Laptop,
  'wrench':           Wrench,
  'scissors':         Scissors,
  'shirt':            Shirt,
  'baby':             Baby,
  'bike':             Bike,
  'pizza':            Pizza,
  'apple':            Apple,
  'leaf':             Leaf,
  'sun':              Sun,
  'moon':             Moon,
  'star':             Star,
  'sparkles':         Sparkles,
  'package':          Package,
  'box':              Box,
  'building':         Building,
  'building-2':       Building2,
  'graduation-cap':   GraduationCap,
  'stethoscope':      Stethoscope,
  'pill':             Pill,
  'dumbbell':         Dumbbell,
  'fuel':             Fuel,
  'receipt':          Receipt,
  'banknote':         Banknote,
  'coins':            Coins,
  'piggy-bank':       PiggyBank,
  'landmark':         Landmark,
  'percent':          Percent,
  'globe':            Globe,
  'map-pin':          MapPin,
  'camera':           Camera,
  'headphones':       Headphones,
  'watch':            Watch,
  'gem':              Gem,
  'hammer':           Hammer,
  'lightbulb':        Lightbulb,
  'wifi':             Wifi,
  'phone':            Phone,
  'mail':             Mail,
  'send':             Send,
  'truck':            Truck,
  'anchor':           Anchor,
  'flame':            Flame,
  'snowflake':        Snowflake,
  'umbrella':         Umbrella,
  'cloud':            Cloud,
  'wind':             Wind,
  'trees':            Trees,
  'flower-2':         Flower2,
  'dog':              Dog,
  'cat':              Cat,
  'salad':            Salad,
  'ice-cream':        IceCream,
  'beer':             Beer,
  'wine':             Wine,
  'sandwich':         Sandwich,
  'soup':             Soup,
  'bookmark':         Bookmark,
}

export default function CategoryIcon({ name, size = 15, className = '' }) {
  const Icon = (name && iconMap[name]) ?? Tag
  return <Icon size={size} className={className} />
}
